package PersonaApp;


/**
* PersonaApp/PersonaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Persona.idl
* lunes 23 de abril de 2018 07:36:42 PM COT
*/

public interface PersonaOperations 
{
  boolean insertarPersona (int id, String nombre, String apellido, String telefono, String direccion, int identificacion);
  String consultarPersona (int identificacion);
  boolean eliminarPersona (int identificacion);
  boolean actualizarPersona (int id, String nombre, String apellido, String telefono, String direccion, int identificacion);
  String listarPersonas ();
  void shutdown ();
} // interface PersonaOperations
