package PersonaApp;


/**
* PersonaApp/Persona.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Persona.idl
* lunes 23 de abril de 2018 07:36:42 PM COT
*/

public interface Persona extends PersonaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Persona
